# Generated by Django 3.1.7 on 2021-05-04 16:02

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0002_auto_20210504_2147'),
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name_plural': 'news'},
        ),
        migrations.AddField(
            model_name='news',
            name='news_instance',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 4, 21, 47, 24, 185024)),
        ),
        migrations.CreateModel(
            name='NewsVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.CharField(blank=True, choices=[('Up', 'Up'), ('Down', 'Down')], max_length=255, null=True)),
                ('vote_instance', models.DateTimeField(default=datetime.datetime(2021, 5, 4, 21, 47, 24, 187019))),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.news')),
                ('reader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reader.reader')),
            ],
        ),
        migrations.CreateModel(
            name='NewsComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/news/comments/')),
                ('file', models.FileField(blank=True, null=True, upload_to='files/news/comments/')),
                ('comment_instance', models.DateTimeField(default=datetime.datetime(2021, 5, 4, 21, 47, 24, 186021))),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.news')),
                ('reader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reader.reader')),
            ],
        ),
    ]
