# Generated by Django 3.1.7 on 2021-05-03 15:52

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, help_text="Phone number must be entered in the format: '000-555555' or '+999-9999999999'.", max_length=255, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '000-555555' or '+999-9999999999'.", regex='(0[0-9]{1,2}-[0-9]{6,6})|([0-9]{10})')])),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/reader/')),
                ('address', models.TextField(blank=True, null=True)),
                ('dob', models.DateField(blank=True, help_text='write in 2010-01-01', null=True)),
                ('is_author', models.BooleanField(default=False)),
                ('keywords', models.TextField(blank=True, help_text='write in keyword1, keyword2, format', null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
